"""Build a Sprint-2 song bundle from an UltraStar chart + audio assets.

A song bundle lives at ``data/songs/<song_id>/`` and is the canonical input
for ``run_reference_pipeline`` and ``analyze_performance``. This module
handles two responsibilities:

1. Parse an UltraStar ``.txt`` chart into a ``ReferenceAnnotation`` so the
   note grid, lyric words, and phonemes line up with what ``align_v2`` and
   ``stars_runner`` expect.
2. Emit / load the per-song ``manifest.json`` so the FastAPI layer can list
   songs and find their precomputed artifacts at runtime.

The phoneme list is generated by a lightweight grapheme-to-phoneme step (CMU
``g2p_en`` if available, otherwise a deterministic fallback that maps each
syllable to a single ``<UNK>`` token). STARS forced-alignment then refines
the timings on the reference vocal in ``run_reference_pipeline``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional

import soundfile as sf

from vocal_coach.schemas import (
    ReferenceAnnotation,
    ReferenceNote,
    ReferenceSection,
    SongManifest,
    StarsMetadataEntry,
    UltraStarMetadata,
)
from vocal_coach.ultrastar import (
    PHRASE_BREAK,
    UltraStarChart,
    UltraStarNote,
    parse_ultrastar,
    words_from_notes,
)


# STARS bilingual phone-set silence token (matches third_party/stars).
STARS_SILENCE_PH = "<SP>"
STARS_BREATH_PH = "<AP>"

# Minimum phoneme duration to avoid STARS BinarizationError.
# STARS uses hop_size=256 @ 24000 Hz → one mel frame = 256/24000 ≈ 10.67 ms.
# Require at least 1.5 frames so start_frame < end_frame after rounding.
_STARS_HOP_S: float = 256.0 / 24000.0
_MIN_PH_DUR_S: float = _STARS_HOP_S * 1.5  # ~16 ms


# ---------------------------------------------------------------------------
# Grapheme-to-phoneme
# ---------------------------------------------------------------------------


def _g2p_word(word: str) -> list[str]:
    """Return CMU-style phonemes for one English word.

    Uses ``g2p_en`` when available (and when its NLTK data dependencies are
    installed); falls back to a single ``<UNK>`` token so the rest of the
    pipeline still has *something* to feed STARS.
    """
    cleaned = re.sub(r"[^A-Za-z']+", "", word)
    if not cleaned:
        return [STARS_SILENCE_PH]
    g2p = _get_g2p_singleton()
    if g2p is None:
        return ["<UNK>"]
    try:
        phones = [p for p in g2p(cleaned) if p.strip()]
    except Exception:
        # g2p_en can raise nltk LookupError when its tagger data isn't
        # available. We don't want to abort the whole song import for this.
        return ["<UNK>"]
    if not phones:
        return ["<UNK>"]
    # g2p_en returns CMU phones with stress digits (AH0/AH1/AH2). STARS's
    # bilingual phone-set carries the same convention, so we keep them.
    return phones


_G2P_SINGLETON = None
_G2P_TRIED = False
_G2P_NLTK_DOWNLOADS = (
    "averaged_perceptron_tagger",
    "averaged_perceptron_tagger_eng",
    "cmudict",
)


def _get_g2p_singleton():
    """Lazy-load the G2p model so ``import vocal_coach.song`` stays cheap."""
    global _G2P_SINGLETON, _G2P_TRIED
    if _G2P_TRIED:
        return _G2P_SINGLETON
    _G2P_TRIED = True
    try:
        from g2p_en import G2p  # type: ignore
    except Exception:
        _G2P_SINGLETON = None
        return None
    # Best-effort download of the NLTK data g2p_en needs. If this fails (no
    # internet, etc.) we'll fall back to <UNK> phonemes per word.
    try:
        import nltk  # type: ignore

        for resource in _G2P_NLTK_DOWNLOADS:
            try:
                nltk.download(resource, quiet=True)
            except Exception:
                pass
    except Exception:
        pass
    try:
        _G2P_SINGLETON = G2p()
    except Exception:
        _G2P_SINGLETON = None
    return _G2P_SINGLETON


# ---------------------------------------------------------------------------
# UltraStar chart -> ReferenceAnnotation
# ---------------------------------------------------------------------------


def _midi_to_name(midi: int) -> str:
    names = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
    return f"{names[midi % 12]}{midi // 12 - 1}"


def _phrase_sections(
    chart: UltraStarChart,
    duration_s: float,
) -> list[ReferenceSection]:
    """Convert ``- <beat>`` phrase breaks into named sections."""
    boundaries: list[float] = [0.0]
    for pb in chart.phrase_breaks:
        boundaries.append(pb.end_s)
    if not chart.notes:
        return [ReferenceSection(name="Full", start_s=0.0, end_s=duration_s)]
    last_end = chart.notes[-1].end_s
    boundaries.append(max(last_end, duration_s))

    sections: list[ReferenceSection] = []
    for i in range(len(boundaries) - 1):
        start = boundaries[i]
        end = boundaries[i + 1]
        if end <= start:
            continue
        sections.append(
            ReferenceSection(
                name=f"Phrase {i + 1}",
                start_s=start,
                end_s=end,
            )
        )
    if not sections:
        sections = [ReferenceSection(name="Full", start_s=0.0, end_s=duration_s)]
    return sections


def _notes_for_word(
    word: str,
    note_indices: list[int],
    chart_notes: list[UltraStarNote],
    word_index: int,
    word_phones: list[str],
) -> list[ReferenceNote]:
    """Produce ``ReferenceNote`` entries for one word.

    Phonemes are evenly distributed across the word's notes (so a 3-phone
    word sung over 2 notes gets [phones[0], phones[1:]]). STARS will refine
    the actual timings later.
    """
    out: list[ReferenceNote] = []
    n = len(note_indices)
    if n == 0:
        return out

    # Partition phonemes into chunks of size ~ len(phones)/n.
    if word_phones:
        chunk = max(1, len(word_phones) // n)
        chunks: list[list[str]] = []
        for i in range(n):
            if i == n - 1:
                chunks.append(word_phones[i * chunk :])
            else:
                chunks.append(word_phones[i * chunk : (i + 1) * chunk])
    else:
        chunks = [[] for _ in range(n)]

    for slot, note_idx in enumerate(note_indices):
        chart_note = chart_notes[note_idx]
        if chart_note.is_freestyle or chart_note.is_rap:
            # Skip rap/freestyle notes: keep word/phone bookkeeping below but
            # do not score these against pitch.
            continue
        out.append(
            ReferenceNote(
                index=0,  # filled in by caller after concatenation
                start_s=chart_note.start_s,
                end_s=chart_note.end_s,
                midi_pitch=chart_note.midi_pitch,
                note_name=_midi_to_name(chart_note.midi_pitch),
                lyric_word=word,
                word_index=word_index,
                phonemes=chunks[slot] if slot < len(chunks) else [],
            )
        )
    return out


def reference_from_ultrastar(
    chart: UltraStarChart,
    *,
    sample_id: str,
    audio_path: Path,
    sample_rate: int,
    duration_s: float,
    language: str = "English",
) -> ReferenceAnnotation:
    """Build a ``ReferenceAnnotation`` from a parsed UltraStar chart."""
    word_groups = words_from_notes(chart.notes)

    flat_words: list[str] = []
    flat_phones: list[str] = []
    flat_ph2word: list[int] = []
    word_durs: list[float] = []
    ph_durs: list[float] = []
    notes: list[ReferenceNote] = []

    seconds_per_beat = chart.seconds_per_beat

    for word_idx, (word_text, note_indices) in enumerate(word_groups):
        flat_words.append(word_text)
        # Word duration: span from first note start to last note end.
        first_note = chart.notes[note_indices[0]]
        last_note = chart.notes[note_indices[-1]]
        word_dur = max(_MIN_PH_DUR_S, last_note.end_s - first_note.start_s)
        word_durs.append(word_dur)

        phones = _g2p_word(word_text)
        # Even split of word duration across phonemes; clamp each to minimum.
        slice_dur = max(_MIN_PH_DUR_S, word_dur / max(1, len(phones)))
        for ph in phones:
            flat_phones.append(ph)
            flat_ph2word.append(word_idx)
            ph_durs.append(slice_dur)

        word_notes = _notes_for_word(
            word_text, note_indices, chart.notes, word_idx, phones
        )
        notes.extend(word_notes)

    # Reindex notes after potential rap/freestyle skips.
    for i, note in enumerate(notes):
        notes[i] = note.model_copy(update={"index": i})

    # Insert silences (<SP>) between words separated by phrase breaks so
    # the STARS metadata has rest tokens at phrase boundaries (mirrors how
    # the GTSinger pipeline handles the silence remap to <SP>).
    sections = _phrase_sections(chart, duration_s)

    return ReferenceAnnotation(
        sample_id=sample_id,
        audio_path=audio_path.name,
        sample_rate=sample_rate,
        duration_s=duration_s,
        language=language,
        sections=sections,
        words=flat_words,
        phones=flat_phones,
        ph2word=flat_ph2word,
        word_durs_s=word_durs,
        ph_durs_s=ph_durs,
        notes=notes,
    )


# ---------------------------------------------------------------------------
# Manifest IO
# ---------------------------------------------------------------------------


def write_manifest(song_dir: Path, manifest: SongManifest) -> Path:
    """Write ``manifest.json`` into ``song_dir``."""
    out = Path(song_dir) / "manifest.json"
    out.write_text(manifest.model_dump_json(indent=2), encoding="utf-8")
    return out


def load_manifest(song_dir: Path) -> SongManifest:
    """Load ``manifest.json`` from ``song_dir``."""
    path = Path(song_dir) / "manifest.json"
    return SongManifest.model_validate_json(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Sprint-3 sidecar sections.yaml loader
# ---------------------------------------------------------------------------


SECTIONS_SIDECAR_FILENAME = "sections.yaml"


def load_sections_sidecar(song_dir: Path) -> Optional[list[ReferenceSection]]:
    """Load ``sections.yaml`` next to a song bundle (None if not present).

    Schema (see data/songs/<song_id>/sections.yaml)::

        sections:
          - name: "Chorus 1"
            kind: chorus
            start_s: 40.3
            end_s: 52.7

    Returns ``None`` when the sidecar is absent so callers can fall back to
    the auto ``Phrase N`` sections built from UltraStar phrase breaks.
    """
    song_dir = Path(song_dir)
    sidecar = song_dir / SECTIONS_SIDECAR_FILENAME
    if not sidecar.is_file():
        return None
    try:
        import yaml  # type: ignore
    except Exception:
        return None
    data = yaml.safe_load(sidecar.read_text(encoding="utf-8")) or {}
    entries = data.get("sections") or []
    sections: list[ReferenceSection] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        try:
            sections.append(
                ReferenceSection(
                    name=str(entry["name"]),
                    start_s=float(entry["start_s"]),
                    end_s=float(entry["end_s"]),
                    kind=entry.get("kind"),
                )
            )
        except (KeyError, TypeError, ValueError):
            continue
    return sections or None


def apply_sections_sidecar(
    song_dir: Path,
    annotation: ReferenceAnnotation,
) -> ReferenceAnnotation:
    """If ``song_dir/sections.yaml`` exists, replace annotation.sections with it."""
    sections = load_sections_sidecar(song_dir)
    if sections is None:
        return annotation
    return annotation.model_copy(update={"sections": sections})


def scale_annotation_notes_to_audio(
    annotation: ReferenceAnnotation,
    *,
    target_duration_s: float,
    tolerance: float = 1.15,
) -> ReferenceAnnotation:
    """Compress chart note times when the UltraStar span exceeds the audio length.

    Some community charts (e.g. medley editions) list beats that extend far
    beyond the bundled reference vocal.  Misaligned note windows break global
    offset, octave-shift detection, pitch scoring, and the section ribbon.
    """
    if not annotation.notes:
        return annotation
    chart_end = max(n.end_s for n in annotation.notes)
    if chart_end <= 0 or chart_end <= target_duration_s * tolerance:
        return annotation

    scale = target_duration_s / chart_end
    scaled_notes = [
        n.model_copy(
            update={
                "start_s": n.start_s * scale,
                "end_s": n.end_s * scale,
            }
        )
        for n in annotation.notes
    ]
    word_durs = annotation.word_durs_s
    if word_durs:
        word_durs = [d * scale for d in word_durs]
    ph_durs = annotation.ph_durs_s
    if ph_durs:
        ph_durs = [d * scale for d in ph_durs]

    return annotation.model_copy(
        update={
            "notes": scaled_notes,
            "duration_s": target_duration_s,
            "word_durs_s": word_durs,
            "ph_durs_s": ph_durs,
        }
    )


def write_reference_for_song(
    song_dir: Path,
    annotation: ReferenceAnnotation,
    *,
    indent: int = 2,
) -> tuple[Path, Path]:
    """Write ``reference_annotation.json`` and ``stars_metadata.json`` into a song dir."""
    song_dir = Path(song_dir)

    ref_path = song_dir / "reference_annotation.json"
    ref_path.write_text(annotation.model_dump_json(indent=indent), encoding="utf-8")

    stars_entry: StarsMetadataEntry = annotation.to_stars_metadata(
        wav_fn=str((song_dir / annotation.audio_path).resolve()).replace("\\", "/"),
    )
    stars_meta_path = song_dir / "stars_metadata.json"
    stars_meta_path.write_text(
        json.dumps([stars_entry.model_dump(exclude_none=True)], indent=indent, ensure_ascii=False),
        encoding="utf-8",
    )
    return ref_path, stars_meta_path


# ---------------------------------------------------------------------------
# Helpers for the importer script
# ---------------------------------------------------------------------------


def _wav_metadata(audio_path: Path) -> tuple[int, float]:
    """Return (sample_rate, duration_seconds). Falls back to librosa for mp3s."""
    audio_path = Path(audio_path)
    suffix = audio_path.suffix.lower()
    if suffix in {".wav", ".flac", ".ogg"}:
        info = sf.info(str(audio_path))
        return info.samplerate, info.frames / float(info.samplerate)
    # MP3 / m4a etc. — soundfile can't always read these without libsndfile
    # mp3 support, so fall back to librosa which decodes via audioread.
    import librosa  # noqa: F401  (lazy)

    duration = float(librosa.get_duration(path=str(audio_path)))
    sr = int(librosa.get_samplerate(str(audio_path)))
    return sr, duration


def import_ultrastar_song(
    *,
    song_dir: Path,
    chart_filename: Optional[str] = None,
    reference_vocal: Optional[str] = None,
    instrumental: Optional[str] = None,
    song_id: Optional[str] = None,
    midi_offset: int = 0,
) -> tuple[ReferenceAnnotation, SongManifest]:
    """Build ``reference_annotation.json``, ``stars_metadata.json`` and ``manifest.json``.

    Looks for the chart and audio files inside ``song_dir`` (with optional
    overrides). Returns the in-memory ``ReferenceAnnotation`` and
    ``SongManifest`` after writing them to disk.
    """
    song_dir = Path(song_dir).resolve()
    if not song_dir.is_dir():
        raise FileNotFoundError(f"Song directory not found: {song_dir}")

    # Locate the UltraStar .txt chart.
    if chart_filename is None:
        candidates = [
            p for p in song_dir.glob("*.txt") if p.name.lower() != "license.txt"
        ]
        if len(candidates) != 1:
            raise ValueError(
                f"Expected exactly one UltraStar .txt in {song_dir}, "
                f"found {len(candidates)}: {[c.name for c in candidates]}"
            )
        chart_path = candidates[0]
    else:
        chart_path = song_dir / chart_filename

    chart = parse_ultrastar(chart_path, midi_offset=midi_offset)

    # Resolve audio paths.
    if reference_vocal is None:
        for pattern in ("*reference*vocal*", "*ref*vocal*", "*vocal*", "*reference*"):
            matches = sorted(song_dir.glob(pattern))
            audio_matches = [
                m for m in matches
                if m.suffix.lower() in {".wav", ".mp3", ".flac", ".ogg", ".m4a"}
                and "instrumental" not in m.name.lower()
            ]
            if audio_matches:
                ref_path = audio_matches[0]
                break
        else:
            raise FileNotFoundError(
                f"No reference vocal audio found in {song_dir}; pass --reference-vocal"
            )
    else:
        ref_path = song_dir / reference_vocal

    inst_path: Optional[Path]
    if instrumental is None:
        inst_matches = [
            m for m in song_dir.iterdir()
            if m.is_file()
            and m.suffix.lower() in {".wav", ".mp3", ".flac", ".ogg", ".m4a"}
            and "instrumental" in m.name.lower()
        ]
        inst_path = inst_matches[0] if inst_matches else None
    else:
        inst_path = song_dir / instrumental

    sample_rate, duration_s = _wav_metadata(ref_path)
    if song_id is None:
        # ``Losing My Religion`` -> ``losing-my-religion``
        slug = chart.title or song_dir.name
        song_id = re.sub(r"[^A-Za-z0-9]+", "-", slug).strip("-").lower()

    annotation = reference_from_ultrastar(
        chart,
        sample_id=song_id,
        audio_path=ref_path,
        sample_rate=sample_rate,
        duration_s=duration_s,
        language=chart.language or "English",
    )
    # Sprint 3: if a sections.yaml sidecar exists, use it instead of the
    # auto-derived "Phrase N" sections from the chart's phrase breaks.
    annotation = apply_sections_sidecar(song_dir, annotation)

    write_reference_for_song(song_dir, annotation)

    # Preserve any existing precomputed reference paths so re-importing a
    # song that already had build_song.py run on it doesn't clear them.
    existing_manifest_path = song_dir / "manifest.json"
    existing_ref_pitch = None
    existing_ref_stars = None
    existing_ref_loudness = None
    if existing_manifest_path.is_file():
        try:
            _old = SongManifest.model_validate_json(
                existing_manifest_path.read_text(encoding="utf-8")
            )
            existing_ref_pitch = _old.reference_pitch_path
            existing_ref_stars = _old.reference_stars_path
            existing_ref_loudness = _old.reference_loudness_path
        except Exception:
            pass

    manifest = SongManifest(
        song_id=song_id,
        title=chart.title or song_id,
        artist=chart.artist or "",
        language=chart.language or "English",
        chart_path=chart_path.name,
        reference_vocal_path=ref_path.name,
        instrumental_path=inst_path.name if inst_path else None,
        duration_s=duration_s,
        ultrastar=UltraStarMetadata(
            bpm=chart.bpm,
            gap_ms=chart.gap_ms,
            audio_ref=chart.audio_ref,
            cover=chart.cover,
            background=chart.background,
            edition=chart.edition,
            midi_offset=midi_offset,
        ),
        reference_pitch_path=existing_ref_pitch,
        reference_stars_path=existing_ref_stars,
        reference_loudness_path=existing_ref_loudness,
    )
    write_manifest(song_dir, manifest)
    return annotation, manifest


__all__ = [
    "STARS_SILENCE_PH",
    "STARS_BREATH_PH",
    "PHRASE_BREAK",
    "import_ultrastar_song",
    "load_manifest",
    "reference_from_ultrastar",
    "write_manifest",
    "write_reference_for_song",
]
